### ISSUE TITLE
Keep the module backward compatible with v12

### ISSUE THREAD

**Issue by r-valyar** [dev7355608/manage-player-targets#4]
This is more of a recommendation than an issue. It concerns the inability to update to the latest version due to the requirement for Foundry v13. Many users may not feel comfortable transitioning to an unstable version immediately, or even several months after its release, so it will be great if you keep it also compatible with v12 or provide v12 version for those who are not moving to v13 in case the new version has backward incompatible code.

![image](https://github.com/user-attachments/assets/20de8358-4cf7-4c53-a253-c4c1fef46f5a)

**Comment by dev7355608** [comment]
The V13 version of Manage Player Targets doesn't have any more features than the V12 version. It's just an update for compatibility with V13. With changes in V13 it would be too much of a burden to also continue support for V12 and earlier versions. So that's why I dropped support for V12 and earlier. You may ignore this warning. The warning does not mean that something is wrong with your current installation of the module. It just means that there's a newer version available that needs V13.

**Comment by r-valyar** [comment]
@dev7355608  so the recommendation is to lock the module, so it does not check for updates until V13 is out? What prevents to put compatibility for 12 and 13, I think this was possible in the manifest?

**Comment by dev7355608** [comment]
You can lock it if you feel like the warning is too annoying, you just need to remember to unlock it when you update to V13, because the version of Manage Player Targets you have installed now in V12 is not V13 compatible and will break in V13. But you don't need to lock it: you can just ignore the warning. It won't install the new version that is not V12 compatible.

Maintaining V12 and earlier compatibility would have required me to maintain basically twice as much code and css styling rules going forward. I also didn't want risk accidently breaking anything about the module in V12 with a V13 compatibility update.

**Comment by r-valyar** [comment]
Got it. Thanks and agree with the approach in this situation :)
